### ISSUE TITLE
oc project not set

### ISSUE THREAD

**Issue by fwmarkcheung** [OpenShiftDemos/containerizing-apps-2021#3]
I am working on the lab3 to push the image locally to Openshift.  It looks like the project is not set, not even to the default.

[lab-user@studentvm 0 ~]$ oc project
No project has been set. Pass a project name to make that the default.

So I got an error when I executed the following command  

[lab-user@studentvm 0 ~]$ sudo podman tag localhost/wordpress $OS_REGISTRY/$(oc project -q)/w
ordpress
error: no project has been set
Error: error adding 'default-route-openshift-image-registry.apps.summit2021.openshift.open.re
dhat.com//wordpress' to image "localhost/wordpress": invalid reference format

**Comment by thoraxe** [comment]
I have a feeling you have failed to login to the cluster before trying to run `oc project`.

Can you verify with `oc whoami` ?

**Comment by fwmarkcheung** [comment]
No I logged in succesfully.  As I executed, 

[lab-user@studentvm 0 ~]$ oc project
No project has been set. Pass a project name to make that the default.

to verify that the project was not set

**Comment by fwmarkcheung** [comment]
No worries.  It seems to be working fine now.  Not sure what happened last time since I did see the login successful msg.

lab-user@studentvm 0 ~]$ oc login -u $OS_USER $OS_API
Logged into "https://api.summit2021.openshift.open.redhat.com:6443" as "mcheung-redhat.com" u
sing existing credentials.

You have one project on this server: "user-mcheung-redhat-com"

**Comment by thoraxe** [comment]
@fwmarkcheung I know the problem.

IIRC GPTE uses an operator that detects first login and then creates the `user-${USERNAME}` project. My guess is that you logged in and IMMEDIATELY looked for your project. I am going to reopen this issue as a reminder for me to add a note to wait.

**Comment by thoraxe** [comment]
Fixed by 45f2653848d1702eb1ae9ab1f8669f1e433c3716
