### ISSUE TITLE
Failed to connect to DB

### ISSUE THREAD

**Issue by fwmarkcheung** [OpenShiftDemos/containerizing-apps-2021#5]
Working in the last section of the lab.  Got an error msg regarding fail to connect to DB. 

[lab-user@studentvm 0 ~]$ oc get pods
NAME        READY   STATUS    RESTARTS   AGE
mariadb     1/1     Running   0          6m28s
wordpress   1/1     Running   0          6m28s
[lab-user@studentvm 0 ~]$ oc get services
NAME        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
mariadb     ClusterIP   172.30.132.250   <none>        3306/TCP   6m2s
wordpress   ClusterIP   172.30.182.153   <none>        8080/TCP   6m2s
[lab-user@studentvm 0 ~]$ !c
curl -L http://wordpress-user-mcheung-redhat-com.apps.summit2021.openshift.open.redhat.c
om
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Database Error</title>

</head>
<body>
        <h1>Error establishing a database connection</h1>
</body>
</html>

I did not get any error msg from the log:

[lab-user@studentvm 1 ~]$ oc logs -f wordpress
++ dirname /scripts/start.sh
+ MYDIR=/scripts
+ /scripts/config_wordpress.sh
Creating wp-config.php...
+ /usr/sbin/php-fpm
[27-Sep-2021 19:34:41] NOTICE: [pool www] 'user' directive is ignored when FPM is not ru
nning as root
[27-Sep-2021 19:34:41] NOTICE: [pool www] 'group' directive is ignored when FPM is not r
unning as root
+ /usr/sbin/httpd -D FOREGROUND
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, u
sing 10.128.7.35. Set the 'ServerName' directive globally to suppress this message

and the DB seems to be listening (oc logs -f 

021-09-27 19:34:43 0 [Note] /usr/libexec/mysqld: ready for connections.
Version: '10.3.28-MariaDB'  socket: '/tmp/mysql.sock'  port: 0  MariaDB Server
---> 19:34:44     MySQL started successfully

**Comment by thoraxe** [comment]
How long did you wait after the DB container was started? It can take a good bit of time for both Apache and Maria to be "happy." Although it looks like your pods were 6 minutes old. It could be good to try to look inside the Apache container to make sure that it has the correct database connection information. I'm wondering if Apache doesn't have the right ENVs, so the script is created badly, so it can't connect to the DB.

**Comment by fwmarkcheung** [comment]
No worries.  I missed the part we need to create the services before the pods were created.  So the svc env were not injected into the pods as you suspected :)
